Många fixar små
Scouterna/simplesamlphp-module-scoutnetmodule pull request #16
Opened 2019-11-06 21:36 UTC by puggan

Gått igenom koden med phpstorms inspection, och fixat massa sma saker, tex:
* Gjort statiska function av de funktioner som inte använder $this
* definerat retur och paramter typer
* förenklat datastrukturen i removeDiacritics, och tagit bort loopen
* diverse PSR-12 kod-stils ändringar

2019-11-08 20:10 UTC, Klako requested changes
Ett par buggar, annars verkar det fungera.
Testade den nya `removeDiacritics()` för sig självt vilket fungerar najs.

2019-11-08 20:10 UTC, Klako commented on lib/Auth/Source/scoutnetauth.php
> +    protected function login(string $username, string $password): array
Får detta felmeddelande:
```
PHP Fatal error:  Declaration of sspmod_scoutnetmodule_Auth_Source_scoutnetauth::login(string $username, string $password):
array must be compatible with SimpleSAML\\Module\\core\\Auth\\UserPassBase::login($username, $password)
in /var/simplesamlphp/modules/scoutnetmodule/lib/Auth/Source/scoutnetauth.php on line 6
```
Så vi får väl inte ha typdeklarationer :/

2019-11-08 20:10 UTC, Klako commented on lib/Auth/Source/scoutnetauth.php
> +        $authResultObj = json_decode($authResult, true, 512, JSON_THROW_ON_ERROR);
Andra argumentet i `json_decode` gör resultatet till en array medan koden nedan använder det som ett objekt.
Funkar med `false` istället, annars funkar det om man ändrar på allt som använder resultatet.

2019-11-08 20:10 UTC, Klako commented on lib/Auth/Source/scoutnetauth.php
> +        $memberResultObj = json_decode($memberResult, true, 512, JSON_THROW_ON_ERROR);
Samma problem som ovan.
Man får ingen error men några attributer som `group_no` saknas.

2019-11-08 23:09 UTC, puggan commented on lib/Auth/Source/scoutnetauth.php
> +    protected function login(string $username, string $password): array
Sånt brukar jag få information om i editorn, men det funkar ju bara om det är rätt klasser närvarande.

classen "sspmod_core_Auth_UserPassBase" hittade den i vendor/test/phpdoc.php,
det är nog en fake...

Vet du var orginalet av sspmod_core_Auth_UserPassBase finns?

2019-11-08 23:20 UTC, puggan commented on lib/Auth/Source/scoutnetauth.php
> +        $authResultObj = json_decode($authResult, true, 512, JSON_THROW_ON_ERROR);
ah, en bug i inspectorn, koden som lägger till JSON_THROW_ON_ERROR lägger på fel default värde på assoc.

https://github.com/kalessil/phpinspectionsea/issues/1446

2019-11-08 23:43 UTC, puggan commented on lib/Auth/Source/scoutnetauth.php
> +    protected function login(string $username, string $password): array
Det är en alias, för bakåtkompabilitet med tiden före namespaces...
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/_autoload_modules.php#L132

2019-11-08 23:45 UTC, Klako commented on lib/Auth/Source/scoutnetauth.php
> +    protected function login(string $username, string $password): array
Japp, den ligger i https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/core/lib/Auth/UserPassBase.php

2019-11-09 00:00 UTC, puggan commented
Behöver få ordning på min lokala miljö så jag kan testa sakerna, och ev skriva automatiska tester också.

Ser på felen ovan att jag litar väldigt mycket på min editor,
men den brukar ha rätt i andra projeckt :-)

2019-11-09 00:05 UTC, Klako approved these changes

2019-12-12 16:22 UTC, merged